version: "3.7"
x-postgresql-db  : &postgresql-db   nhdplus
x-postgresql-host: &postgresql-host dz_pg
x-postgresql-port: &postgresql-port 5432
x-geoserver-port : &geoserver-port  8080
x-postgrest-port : &postgrest-port  3000
x-postgrest-schc : &postgrest-sch   waterspg
x-postgrest-pass : &postgrest-pass  nhdplus
x-jupyter_port   : &jupyter_port    8888
x-nginx_port     : &nginx_port      8081
x-loading_dock   : &loading_dock    ./loading_dock
x-workspace      : &workspace       ./workspace
x-master_password: &master_password nhdplus
services:
    dz_pg:
        build:
            context: .
            dockerfile: Dockerfile.pg
            shm_size: '2gb'
        hostname: dz_pg
        environment:
            POSTGRES_PASSWORD: *master_password
        ports:
            - target: 5432
              published: *postgresql_port
        networks:
            - dz
        volumes:
            - type: bind
              source: *loading_dock
              target: /loading_dock
            - type: bind
              source: *workspace
              target: /workspace
            - type: volume
              source: pgdata
              target: /var/lib/postgresql/data
            - type: volume
              source: tblspdata
              target: /tblspdata
    dz_gs:
        build:
            context: .
            dockerfile: Dockerfile.gs
        hostname: dz_gs
        environment:
            POSTGRES_PASSWORD: *master_password
        ports:
            - target: 8080
              published: *geoserver_port
        networks:
            - dz
        volumes:
            - type: bind
              source: *loading_dock
              target: /loading_dock
            - type: bind
              source: *workspace
              target: /workspace
            - type: volume
              source: geoserver-data
              target: /opt/geoserver/data_dir
        depends_on:
            - dz_pg
    dz_pr:
        build:
            context: .
            dockerfile: Dockerfile.pr
            shm_size: '2gb'
        hostname: dz_pr
        environment:
            POSTGRESQL_HOST: *postgresql-host
            POSTGRESQL_PORT: *postgresql-port
            POSTGRESQL_DB: *postgresql-db
            POSTGREST_SCH: *postgrest-sch
            POSTGREST_PASS: *postgrest-pass
        ports:
            - target: 3000
              published: *postgrest_port
        networks:
            - dz
        volumes:
            - type: bind
              source: *loading_dock
              target: /loading_dock
        depends_on:
            - dz_pg
    dz_jp:
        build:
            context: .
            dockerfile: Dockerfile.jp
        hostname: dz_jp
        environment:
            POSTGRES_PASSWORD: *master_password
        ports:
            - target: 8888
              published: *jupyter_port
        networks:
            - dz
        volumes:
            - type: bind
              source: *loading_dock
              target: /loading_dock
            - type: bind
              source: *workspace
              target: /workspace
            - type: volume
              source: jupyter
              target: /opt/conda/etc/jupyter
            - type: volume
              source: home-jovyan
              target: /home/jovyan
        depends_on:
            - dz_pg
    dz_ng:
        build:
            context: .
            dockerfile: Dockerfile.ng
        hostname: dz_ng
        environment:
            POSTGRESQL_HOST: *postgresql-host
            POSTGRESQL_PORT: *postgresql-port
            POSTGRESQL_DB: *postgresql-db
            POSTGREST_SCH: *postgrest-sch
            POSTGREST_PASS: *postgrest-pass
            JUPYTER_PORT: *jupyter_port
            POSTGREST_PORT: *postgrest_port
            GEOSERVER_PORT: *geoserver_port
            NGINX_PORT: *nginx_port
        ports:
            - target: 8081
              published: *nginx_port
        networks:
            - dz
        volumes:
            - type: bind
              source: *loading_dock
              target: /loading_dock
            - type: bind
              source: *workspace
              target: /workspace
        depends_on:
            - dz_pg
            - dz_gs
            - dz_pr
networks:
    dz:
        driver: bridge
volumes:
    tblspdata:
    pgdata:
    geoserver-data:
    jupyter:
    home-jovyan:
